# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import handle_new_frame_pb2 as handle__new__frame__pb2


class FrameProcedureStub(object):
    """service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleNewFrame = channel.unary_unary(
                '/FrameProcedure/HandleNewFrame',
                request_serializer=handle__new__frame__pb2.Frame.SerializeToString,
                response_deserializer=handle__new__frame__pb2.Empty.FromString,
                )


class FrameProcedureServicer(object):
    """service
    """

    def HandleNewFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameProcedureServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleNewFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleNewFrame,
                    request_deserializer=handle__new__frame__pb2.Frame.FromString,
                    response_serializer=handle__new__frame__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FrameProcedure', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FrameProcedure(object):
    """service
    """

    @staticmethod
    def HandleNewFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FrameProcedure/HandleNewFrame',
            handle__new__frame__pb2.Frame.SerializeToString,
            handle__new__frame__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
